# Disable LGTM's built-in query to detect unsafe uses of gmtime; there's a
# custom query to check for that
queries:
  - exclude: cpp/potentially-dangerous-function

extraction:
  cpp:
    prepare:
      packages:
        - autoconf-archive
        - openjdk-8-jdk-headless
    after_prepare:
      - export PATH=/usr/lib/jvm/java-8-openjdk-amd64/bin/:$PATH
      - export LD_LIBRARY_PATH=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server:$LD_LIBRARY_PATH
      - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

      - cd /tmp && wget https://ftp.gnu.org/gnu/bison/bison-3.7.6.tar.gz && tar -xzf bison-3.7.6.tar.gz
      - cd /tmp/bison-3.7.6 && ./configure --prefix=/tmp/bison && make all install
      - export PATH=/tmp/bison/bin/:$PATH
