language: c
git:
  submodules: false

os: linux

cache:
  apt: true

services:
  - docker

addons:
  apt:
    sources:
      - sourceline: 'deb http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_14.04 ./'
        key_url: 'http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_14.04/Release.key'
    packages:
      - autoconf-archive
      - bison
      - docbook-xsl
      - flex
      - gradle
      - libcap-dev
      - libdbd-sqlite3
      - libdbi0-dev
      - libesmtp-dev
      - libglib2.0-dev
      - libhiredis-dev
      - libivykis-dev
      - librabbitmq-dev
      - libmongoc-dev
      - libjson0-dev
      - libnet1-dev
      - libriemann-client-dev
      - librdkafka-dev
      - libwrap0-dev
      - pkg-config
      - sqlite3
      - xsltproc
      - criterion-dev
      - libmaxminddb-dev
      - libxml2-utils
      - doxygen
      - libsnmp-dev
      - ninja-build
      - snmptt
install:
      - python2 -m pip install --user --cache-dir=$PWD/pip-cache -r requirements.txt
      - python2 -m pip list
before_script:
  - echo 'Europe/Budapest' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - ./autogen.sh
  - unset PYTHON_CFLAGS # HACK
  - if [ "$CC" = "gcc" ]; then
      EXTRA_WARN="--enable-extra-warnings";
    fi
  - CONFIGURE_FLAGS="
      CFLAGS=-Werror
      --prefix=$HOME/install/syslog-ng
      --with-ivykis=internal
      --with-jsonc=system
      --disable-env-wrapper
      --disable-memtrace
      --enable-tcp-wrapper
      --enable-linux-caps
      --disable-sun-streams
      --enable-all-modules
      --disable-sql
      --enable-pacct
      --enable-manpages
      --enable-force-gnu99
      --with-python=2
      $EXTRA_WARN
      $DISABLE_MONGODB
      "
  - ./configure $CONFIGURE_FLAGS

matrix:
  include:
    - env: B=distcheck
      dist: trusty
      compiler: gcc
      script:
        - set -e
        - . tests/build-log-cflags-propagation.sh;
        - export DISTCHECK_CONFIGURE_FLAGS="$CONFIGURE_FLAGS";
        - exec_prop_check "make distcheck -j 3 V=1"
      after_script:
        - find . -name test-suite.log | xargs cat

    - env: B=autotools-clang
      dist: trusty
      compiler: clang
      script:
        - set -e
        - python2 -m pip install --user --cache-dir=$PWD/pip-cache pre-commit-hooks
        - make --keep-going -j $(nproc) || make V=1 install;
        - make install
        - . scripts/get-libjvm-path.sh;
        - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$JNI_LIBDIR";
        - make pytest-self-check
        - make python-pep8
        - make python-pylint
        - make pytest-linters
        - make VERBOSE=1 func-test
        - make pytest-check

    - env: B=style-check
      dist: trusty
      sudo: required
      addons:
      before_install:
      - docker pull balabit/syslog-ng-devshell
      install:
      before_script:
      script:
      - set -e
      - ./dbld/rules run-devshell RUN_COMMAND="cd /source && astyle --version && scripts/style-checker.sh format"
      - git diff --exit-code

    - env: B=copyright-check
      sudo: false
      compiler: gcc
      install:
      before_script:
      script:
        - set -e
        - export COPYRIGHTVERBOSITY=1
        - tests/copyright/check.sh . .

    - env: B=commits-check
      sudo: false
      compiler: gcc
      install:
      before_script:
      git:
        submodules: false
        depth: false
      script:
        - tests/commits/check.sh "${TRAVIS_COMMIT_RANGE}"

    - env: B=cmake-submodules-and-pytest
      compiler: gcc
      dist: trusty
      sudo: required
      before_script:
      git:
        submodules: true
      script:
        - set -e
        - python2 -m pip install --user --cache-dir=$PWD/pip-cache pre-commit-hooks
        - mkdir build
        - cd build
        - cmake
            -DCMAKE_C_FLAGS=-Werror
            -DPYTHON_VERSION=2
            -DCMAKE_INSTALL_PREFIX=$HOME/install/syslog-ng
            ..
        - make --keep-going -j $(nproc) all check install
        - make pytest-self-check
        - make python-pep8
        - make python-pylint
        - make pytest-linters
        - make VERBOSE=1 func-test
        - make pytest-check

    - env: B=cmake
      compiler: clang
      dist: trusty
      sudo: required
      before_script:
      script:
        - set -e
        - mkdir build
        - cd build
        - cmake
            -G Ninja
            -DCMAKE_C_FLAGS=-Werror
            -DPYTHON_VERSION=2
            -DCMAKE_INSTALL_PREFIX=$HOME/install/syslog-ng
            ..
        - ninja all check install

    - env: B=cmake-arm
      compiler: gcc
      sudo: required
      arch: arm64
      addons:
        apt:
          packages:
            - autoconf-archive
            - bison
            - docbook-xsl
            - flex
            - gradle
            - libcap-dev
            - libcurl4-openssl-dev
            - libdbd-sqlite3
            - libdbi0-dev
            - libesmtp-dev
            - libglib2.0-dev
            - libhiredis-dev
            - libivykis-dev
            - librabbitmq-dev
            - libmongoc-dev
            - libjson-c-dev
            - python-dev
            - python-pip
            - python-setuptools
            - libnet1-dev
            - libriemann-client-dev
            - librdkafka-dev
            - libwrap0-dev
            - pkg-config
            - sqlite3
            - xsltproc
            - libmaxminddb-dev
            - libxml2-utils
            - doxygen
            - libsnmp-dev
      git:
        submodules: false
      before_script:
      script:
        - set -e
        - git clone https://github.com/Snaipe/Criterion.git -b v2.3.3
        - cd Criterion
        - git submodule update --init
        - cmake .
        - make all
        - sudo make install
        - cd ..
        - mkdir build
        - cd build
        - cmake
            -DCMAKE_C_FLAGS=-Werror
            -DPYTHON_VERSION=2
            -DCMAKE_INSTALL_PREFIX=$HOME/install/syslog-ng
            ..
        - make --keep-going -j $(nproc) all install
        - ctest -j $(nproc) --output-on-failure

    - env: B=bionic-python3
      compiler: gcc
      dist: bionic
      sudo: required
      addons:
        apt:
          sources:
            - sourceline: 'deb http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_18.04 ./'
              key_url: 'http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_18.04/Release.key'
          packages:
            - autoconf-archive
            - bison
            - docbook-xsl
            - flex
            - gradle
            - libcap-dev
            - libdbd-sqlite3
            - libdbi0-dev
            - libesmtp-dev
            - libglib2.0-dev
            - libhiredis-dev
            - librabbitmq-dev
            - libmongoc-dev
            - libjson-c-dev
            - libnet1-dev
            - libriemann-client-dev
            - librdkafka-dev
            - libwrap0-dev
            - pkg-config
            - sqlite3
            - xsltproc
            - criterion-dev
            - libmaxminddb-dev
            - libxml2-utils
            - doxygen
            - libsnmp-dev
            - snmptrapd
            - python3
            - python3-pip
            - python3-setuptools
            - openjdk-8-jdk
            - openjdk-8-jre
      install:
        - python3 -m pip install --user -r requirements.txt
        - export PATH=`echo $PATH | sed -r 's|:/usr/local/lib/jvm/openjdk11/bin||'`
        - sudo update-java-alternatives --set java-1.8.0-openjdk-amd64
      git:
        submodules: true
      before_script:
        - echo 'Europe/Budapest' | sudo tee /etc/timezone
        - sudo dpkg-reconfigure --frontend noninteractive tzdata
        - ./autogen.sh
        - unset PYTHON_CFLAGS # HACK
        - CONFIGURE_FLAGS="
            CFLAGS=-Werror
            --prefix=$HOME/install/syslog-ng
            --with-ivykis=internal
            --with-jsonc=system
            --disable-env-wrapper
            --disable-memtrace
            --enable-tcp-wrapper
            --enable-linux-caps
            --disable-sun-streams
            --enable-all-modules
            --disable-mongodb
            --disable-sql
            --enable-pacct
            --enable-manpages
            --enable-force-gnu99
            --with-python=3
            "
        - ./configure $CONFIGURE_FLAGS
      script:
        - set -e
        - make V=1 -j $(nproc)
        - make V=1 check
        - make install
        - make pytest-self-check
        - make python-pep8
        - make python-pylint
        - make pytest-linters
        - make VERBOSE=1 func-test
        - make pytest-check

branches:
  except:
    - /wip/
notifications:
  irc:
    channels:
      - "irc.freenode.org#balabit"
  webhooks:
      urls:
        - https://webhooks.gitter.im/e/1c6e3a6f10348748585a
      on_success: always  # options: [always|never|change] default: always
      on_failure: always  # options: [always|never|change] default: always
      on_start: true     # default: false
