apiVersion: v1
kind: Service
metadata:
  name: {{ include "syslog-ng.fullname" . }}
  labels:
    {{- include "syslog-ng.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.service.type "externalip" }}
  
  {{- with .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 3 }}
  {{- end }}
  {{- else}}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
    - name: udp-port
      port: 514
      targetPort: 514
      protocol: UDP
    - name: tcp-port
      port: 601
      targetPort: 601
      protocol: TCP 
  selector:
    {{- include "syslog-ng.selectorLabels" . | nindent 4 }}
