/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_syslog_ng_LogDestination */

#ifndef _Included_org_syslog_ng_LogDestination
#define _Included_org_syslog_ng_LogDestination
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_syslog_ng_LogDestination
 * Method:    getOption
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_syslog_1ng_LogDestination_getOption
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_syslog_ng_LogDestination
 * Method:    getTemplateOptionsHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_syslog_1ng_LogDestination_getTemplateOptionsHandle
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
