/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_syslog_ng_LogTemplate */

#ifndef _Included_org_syslog_ng_LogTemplate
#define _Included_org_syslog_ng_LogTemplate
#ifdef __cplusplus
extern "C" {
#endif
#undef org_syslog_ng_LogTemplate_LTZ_LOCAL
#define org_syslog_ng_LogTemplate_LTZ_LOCAL 0L
#undef org_syslog_ng_LogTemplate_LTZ_SEND
#define org_syslog_ng_LogTemplate_LTZ_SEND 1L
/*
 * Class:     org_syslog_ng_LogTemplate
 * Method:    create_new_template_instance
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_syslog_1ng_LogTemplate_create_1new_1template_1instance
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_syslog_ng_LogTemplate
 * Method:    compile
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_syslog_1ng_LogTemplate_compile
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_syslog_ng_LogTemplate
 * Method:    format
 * Signature: (JJJI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_syslog_1ng_LogTemplate_format
  (JNIEnv *, jobject, jlong, jlong, jlong, jint);

/*
 * Class:     org_syslog_ng_LogTemplate
 * Method:    unref
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_syslog_1ng_LogTemplate_unref
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
