/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_syslog_ng_LogMessage */

#ifndef _Included_org_syslog_ng_LogMessage
#define _Included_org_syslog_ng_LogMessage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_syslog_ng_LogMessage
 * Method:    unref
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_syslog_1ng_LogMessage_unref
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_syslog_ng_LogMessage
 * Method:    getValue
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_syslog_1ng_LogMessage_getValue
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
